import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '../styles/globals.css';
import { Header, Sidebar } from '@/components';
import { NUIProviders } from '@/provider';

const poppins = Poppins({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'BigPM',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} no-scrollbar antialiased`}>
        <NUIProviders>
          <Header />
          <div className="mt-0.5 flex">
            <Sidebar />
            <div className="w-full overflow-x-auto bg-main-blue">
              <div className="w-full overflow-auto sm:h-[calc(99vh-60px)]">
                <div className="h-[calc(100vh - 120px)] relative mx-auto flex w-full overflow-auto overflow-y-auto">
                  <div className="w-full">{children}</div>
                </div>
              </div>
            </div>
          </div>
        </NUIProviders>
      </body>
    </html>
  );
}
