import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '../styles/globals.css';
import { Header, Sidebar } from '@/components';

const poppins = Poppins({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'BigPM',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} no-scrollbar antialiased`}>
        <Header />
        <div className="flex mt-0.5">
          <Sidebar />
          <div className="w-full overflow-x-auto bg-secondary">
            <div className="overflow-auto sm:h-[calc(99vh-60px)]">
              <div className="h-[calc(100vh - 120px)] relative mx-auto flex w-full justify-center overflow-auto overflow-y-auto">
                <div className="w-full md:max-w-6xl">{children}</div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
